### ISSUE TITLE
fc层的分类数是不是有问题？

### ISSUE THREAD

**Issue by fhqjwyk** [ice-tong/pytorch-captcha#4]
self.fc = nn.Linear(512x11x6, self.num_classxself.num_char)
最后的分类数为什么是36x4呢，感觉应该是36^4

**Comment by ice-tong** [comment]
因为这是4标签36分类，即每张验证码对应4个标签（四个字符）。

**Comment by fhqjwyk** [comment]
> 因为这是4标签36分类，即每张验证码对应4个标签（四个字符）。

知道了，谢谢
