### ISSUE TITLE
大佬，你好，怎样才能联系到您，有事请教，谢谢

### ISSUE THREAD

**Issue by haihaihaiererer** [ice-tong/pytorch-captcha#6]
老大，你好，怎样才能联系到您，有事请教，谢谢

**Comment by ice-tong** [comment]
有问题可以直接在 issue 里面讨论

**Comment by haihaihaiererer** [comment]
我这里有一个验证码识别的项目，不知道，您是否有兴趣，帮忙处理一下，是有偿的，谢谢。

**Comment by ice-tong** [comment]
> 我这里有一个验证码识别的项目，不知道，您是否有兴趣，帮忙处理一下，是有偿的，谢谢。

不好意思，最近比较忙没有空余时间。如果你碰到了具体的问题，可以在这讨论，看到了会及时回复。😂
