### ISSUE TITLE
大佬你好 我想问下 模型结构为什么这么设计？我尝试更改结构效果没您给出的这个好！

### ISSUE THREAD

**Issue by yangmoi** [ice-tong/pytorch-captcha#7]

**Comment by ice-tong** [comment]
模型结构随便设计的，你可以用 torchvision 里面预先实现的模型比如 resnet50 这种。

你自己设计的模型不太好，这个很难说，只要有 conv bn relu 这三种，基本上都能够训练出来。也有可能是你训练的策略，参数等因素有影响。

**Comment by yangmoi** [comment]
> 模型结构随便设计的，你可以用 torchvision 里面预先实现的模型比如 resnet50 这种。
> 
> 你自己设计的模型不太好，这个很难说，只要有 conv bn relu 这三种，基本上都能够训练出来。也有可能是你训练的策略，参数等因素有影响。



> 模型结构随便设计的，你可以用 torchvision 里面预先实现的模型比如 resnet50 这种。
> 
> 你自己设计的模型不太好，这个很难说，只要有 conv bn relu 这三种，基本上都能够训练出来。也有可能是你训练的策略，参数等因素有影响。

好嘞谢谢
